version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@1.0.1

jobs:
  build-and-test:
    executor: python/default
    environment:
      DJANGO_ENV: production
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python manage.py test
          name: Test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
      - run:
          command: heroku run python manage.py migrate --app $HEROKU_APP_NAME
          name: Migrate database
workflows:
  main:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
            filters:
          branches:
            only:
              - master
